apiVersion: apps/v1
kind: Deployment
metadata:
  name: maktaba-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maktaba-api
  template:
    metadata:
      labels:
        app: maktaba-api
    spec:
      containers:
        - name: api
          image: maktaba-api:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: maktaba-config
            - secretRef:
                name: maktaba-secret
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: maktaba-api
spec:
  type: LoadBalancer
  selector:
    app: maktaba-api
  ports:
    - port: 4000
      targetPort: 4000
