apiVersion: apps/v1
kind: Deployment
metadata:
  name: maktaba-db
spec:
  selector:
    matchLabels:
      app: maktaba-db
  template:
    metadata:
      labels:
        app: maktaba-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        envFrom:
        - secretRef:
            name: maktaba-secret
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: maktaba-db
spec:
  selector:
    app: maktaba-db
  ports:
  - port: 5432
    targetPort: 5432
